# Generated by Django 4.2.3 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials_images'),
        ),
    ]
