# Generated by Django 4.2.3 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Ссылка на статью'),
        ),
    ]
