# Generated by Django 4.2.3 on 2023-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('title', models.CharField(max_length=262, verbose_name='Заголовок страницы')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('link', models.URLField(verbose_name='Сссылка на проект')),
                ('image', models.ImageField(upload_to='portfolio_images', verbose_name='Изображение проекта')),
            ],
        ),
    ]
