# Generated by Django 4.2.3 on 2023-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_skills_alter_comment_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя услуги')),
                ('description', models.TextField(verbose_name='Подробности услуги')),
                ('image', models.ImageField(upload_to='service_images')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
